### PR TITLE
Tried updating file to send folders.

### PR DESCRIPTION
**Pull request by py-ranoid**
Can't figure out how to debug my code. Nautilus error logs can't be found anywhere. I'm making a zip out of each folder and adding that to files_new

### CODE REVIEW

**Comment by forabi** [comment]
> Can't figure out how to debug my code. Nautilus error logs can't be found anywhere.

Have you tried launching Nautilus from a terminal instance? I haven't used GNOME or Nautilus in a while so I'm not sure if that would work.

I'll have to trust you on this because, like I said, I'm no longer using Nautilus 😄 
Ping me if the PR is ready to merge.

**Comment by py-ranoid** [comment]
Nope. I don't know how to launch Nautilus from a Terminal Instance.

**Comment by forabi** [comment]
Simply launch a terminal and type:

nautilus

And hit Enter. The logs should be show in the terminal window.

**Comment by py-ranoid** [comment]
It works now. Good to go :+1:

**Comment by py-ranoid** [comment]
Hey. Updated the README in another pull request.

**Pull request merged**
